services:
  be:
    build: ./be
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
  redis:
    image: redis
    ports:
      - "6379:6379"
  fe:
    build: ./fe
    environment:
      REACT_APP_BE_API_URL: "http://127.0.0.1:8000"
    ports:
      - "80:3000"
